Edit cohort
FACG5/gsgca-project pull request #41
Opened 2018-09-17 11:23 UTC by lubnaabd

2018-09-17 11:39 UTC, NouraldinS requested changes

2018-09-17 11:39 UTC, NoureldeanSaed commented on public/js/editCohort.js
> +const nameerror = document.getElementById('nameerror');
Camelcase those.

2018-09-17 11:39 UTC, NoureldeanSaed commented on public/js/editCohort.js
> +    const imgURl = imgURls.value;
So you've written what's above all in lowercase, and here you say `imgURl`? Fix your naming cases.

2018-09-17 11:39 UTC, NoureldeanSaed commented on public/js/editCohort.js
> +    const cohortID = JSON.parse(ID);
`id` not `ID`.

2018-09-17 11:39 UTC, NoureldeanSaed commented on public/js/editCohort.js
> +      .then((response) => { response.json(); })
either
```js
.then((response) => response.json())
```
or
```js
.then((response) => {
  return response.json();
}
```
Don't mix up both.

2018-09-17 11:39 UTC, NoureldeanSaed commented on src/controllers/editcohort.js
> +  const cohortID = JSON.parse(req.params.id);
Destructure id before using it here, and rename your `cohortID` to `cohortId`.

2018-09-17 11:39 UTC, NoureldeanSaed commented on src/database/queries/editcohort.js
> +const editCohorts = (name, description, githublink, imgURl, cohortID) => new Promise((resolve, reject) => {
Don't pass all of these as parameters, pass them to this function as one object and destructure them inside the `editCohorts`.
i.e.
```js
// Callee file
editCohorts({ name, description, githubLink, imgUrl, cohortId });

// editCohort.js
const editCohorts = (cohortData) => {
  const { name, description, githublink, imgURl, cohortID } = cohortData;
...
```
Too, rename your `githublink` to `githubLink`, your `imgURl` to `imgUrl` or `iMgUrL`, your `cohortID` to `cohortId`, and your `editcohort.js` to `editCohorts.js`

2018-09-17 11:39 UTC, NoureldeanSaed commented on src/views/cohort.hbs
>              Edit </a>
Fix indentation.

2018-09-17 11:39 UTC, NoureldeanSaed commented on src/views/editcohort.hbs
> +        {{#each results}}
Fix indentation .

2018-09-17 13:39 UTC, HemaSAli approved these changes

2018-09-17 13:51 UTC, ali-7 approved these changes

2018-09-17 13:56 UTC, NouraldinS requested changes

2018-09-17 13:56 UTC, NoureldeanSaed commented on src/controllers/editcohort.js
> +
Rename file to `editCohort.js`.

2018-09-17 13:56 UTC, NoureldeanSaed commented on src/database/queries/editcohort.js
> +const dbconnection = require('../db_connection');
Delete unused file.

2018-09-18 06:39 UTC, NouraldinS approved these changes

2018-09-18 06:39 UTC, merged