Add project
FACG5/gsgca-project pull request #51
Opened 2018-09-18 19:11 UTC by ali-7

relates to #10

2018-09-18 19:20 UTC, NouraldinS requested changes

2018-09-18 19:20 UTC, NouraldinS commented on public/js/projects.js
>  const students = () => {
You have repeated functions in other files, like your displayErr function, checkName, check* ... etc with your `cohort.js`. Do not repeat functions, reuse.

2018-09-18 19:20 UTC, NouraldinS commented on src/database/queries/addProject.js
> +    values: [newProject.nameVal, newProject.descriptionVal, newProject.gitLinkVal,
Fix indentation.

2018-09-18 20:17 UTC, ali-7 commented on src/database/queries/addProject.js
> +    values: [newProject.nameVal, newProject.descriptionVal, newProject.gitLinkVal,
there's no indentation issue

2018-09-18 20:21 UTC, NoureldeanSaed commented on src/database/queries/addProject.js
> +    values: [newProject.nameVal, newProject.descriptionVal, newProject.gitLinkVal,
There is, you cannot add newlines after certain commas in some array\object and leave the rest, it is either you add new lines after commas, or you don't.

2018-09-18 21:10 UTC, ali-7 commented on public/js/projects.js
>  const students = () => {
i add the same function i used in one file

2018-09-19 06:34 UTC, NouraldinS approved these changes
@ali-7 You can merge this one.

2018-09-19 07:33 UTC, merged