Bug
FACG5/gsgca-project pull request #61
Opened 2018-09-19 12:37 UTC by lubnaabd

2018-09-19 13:18 UTC, ali-7 approved these changes

2018-09-19 13:18 UTC, HemaSAli approved these changes

2018-09-20 07:29 UTC, NoureldeanSaed commented
@lubnaabd A branch that is called `bug`, assigned to no issue, and with 19 files changed?

2018-09-20 10:54 UTC, ali-7 requested changes

2018-09-20 10:54 UTC, ali-7 commented on src/views/cohortWebsite.hbs
>  <section class="section2">
fix indentation

2018-09-20 10:55 UTC, NouraldinS approved these changes

2018-09-20 11:00 UTC, ali-7 approved these changes

2018-09-20 11:01 UTC, merged