Students project
FACG5/gsgca-project pull request #68
Opened 2018-09-21 12:22 UTC by lubnaabd

relates to #67

2018-09-21 12:28 UTC, ali-7 approved these changes

2018-09-21 14:19 UTC, NouraldinS requested changes
Do not abbreviate the names of your functions nor your variables.

2018-09-21 14:19 UTC, NoureldeanSaed commented on public/js/studentProject.js
> +const URL = window.location.href;
Rename to `url`.

2018-09-21 14:19 UTC, NoureldeanSaed commented on public/js/studentProject.js
> +const addStudents = () => {
Rename to `toggleAddStudents`.

2018-09-21 14:19 UTC, NoureldeanSaed commented on public/js/studentProject.js
> +  const deleteProjectData = { std_project: button.id };
Rename `std_project` to `studentProject`.

2018-09-21 14:19 UTC, NoureldeanSaed commented on public/js/studentProject.js
> +const deleteStudentButton = document.querySelectorAll('.delete');
Rename to `deleteStudentButtons`.

2018-09-21 14:19 UTC, NoureldeanSaed commented on public/js/studentProject.js
> +  const deleteProjectData = { std_project: button.id };
And anyway, how does it make sense to assign `studentProject` the value of `button.id`? What are you doing here?

2018-09-21 14:19 UTC, NoureldeanSaed commented on public/js/studentProject.js
> +  const deleteProjectData = { std_project: button.id };
@lubnaabd I dug up what you were trying to achieve, firstly, line 9 `const deleteStudentButton = document.querySelectorAll('.delete');` isn't selecting any buttons, it is selecting anchor elements. So it is either you change your anchors to buttons, or change the variable's name to `deleteStudentAnchors` and act accordingly, then you're saying:
```js
const deleteProjectData = { std_project: button.id };
```
What is `std_project`? in your `src/views/cohortStudents.hbs` on line 28 you've said:
```hbs
<a class="delete" id="{{std_id}}">Delete</a>
```
Which by the way needs to be renamed to `studentId`.
You're passing here a student's ID, then assigning it to `std_project`? Why? What made sense when you've made this?

2018-09-21 14:19 UTC, NoureldeanSaed commented on public/js/studentProject.js
> +  const stdId = selector[selector.selectedIndex].value;
Rename to `studentId`.

2018-09-21 14:19 UTC, NoureldeanSaed commented on src/controllers/studentsProject.js
> +const { deleteStdProjectQuery } = require('../database/queries/deleteStdProject');
Rename to `deleteStudentProjectQuery`.

2018-09-21 14:19 UTC, NoureldeanSaed commented on src/controllers/studentsProject.js
> +const { addStdProjectQuery } = require('../database/queries/addStdProject');
Rename to `addStudentProjectQuery`.

2018-09-21 14:19 UTC, NoureldeanSaed commented on src/controllers/studentsProject.js
> +exports.addStdProject = (req, response, next) => {
Rename to `addStudentProject`.

2018-09-21 14:19 UTC, NoureldeanSaed commented on src/controllers/studentsProject.js
> +exports.deleteStdProject = (req, response, next) => {
Rename to `deleteStudentProject`.

2018-09-21 14:19 UTC, NoureldeanSaed commented on src/database/queries/addStdProject.js
> +const dbconnection = require('../db_connection');
Rename to `dbConnection` and rename file to `addStudentProject`.

2018-09-21 14:19 UTC, NoureldeanSaed commented on src/database/queries/deleteStdProject.js
> +const dbconnection = require('../db_connection');
Rename to `dbConnection` and rename file to `deleteStudentProject`.

2018-09-21 14:19 UTC, NoureldeanSaed commented on src/views/cohortStudents.hbs
> +          <a class="edit" href = "/admin/cohorts/{{cohort_id}}/editStudent/{{std_id}}"id="{{std_id}}">Edit</a>
Rename `std_id` to `studentId`.

2018-09-21 14:19 UTC, NoureldeanSaed commented on src/views/projectsPage.hbs
> +          <a class="student" href="/admin/{{../projectsType}}/{{id}}/projects/student/{{cohort_id}}">
Rename `cohort_id` to `cohortId`.

2018-09-21 14:19 UTC, NoureldeanSaed commented on src/views/studentsProject.hbs
> +        <td>{{student_name}}</td>
Rename to `studentName`.

2018-09-21 22:13 UTC, HemaSAli approved these changes

2018-09-22 15:05 UTC, NouraldinS approved these changes

2018-09-22 15:47 UTC, merged